### Find all soldiers
GET {{host}}/api/v1/soldiers

### Find soldier by ID
GET {{host}}/api/v1/soldiers/1

### Create soldier
POST {{host}}/api/v1/soldiers
Content-Type: application/json
Authorization: TESTE

{
  "cpf": "987654321",
  "name": "Ricardo",
  "tribe": "HUMANO",
  "weapon": "Espada"
}

### Update soldier
PUT {{host}}/api/v1/soldiers/123456789
Content-Type: application/json

{
  "name": "Ricardo",
  "tribe": "Humano",
  "weapon": "Espada"
}

### Delete soldier by CPF
DELETE {{host}}/api/v1/soldiers/123456789
